In [1]:
import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

import kagglehub
# kagglehub.dataset_download('<owner>/<dataset-slug>')

/kaggle/input/datasets/saurabhbadole/restaurant-tips-dataset/tips.csv


# import libraries

In [2]:
import numpy as np
import pandas as pd

In [3]:
tips = pd.read_csv('/kaggle/input/datasets/saurabhbadole/restaurant-tips-dataset/tips.csv')

In [4]:
tips.head()

,total_bill,tip,sex,smoker,day,time,size
0,16.99,1.01,Female,No,Sun,Dinner,2
1,10.34,1.66,Male,No,Sun,Dinner,3
2,21.01,3.50,Male,No,Sun,Dinner,3
3,23.68,3.31,Male,No,Sun,Dinner,2
4,24.59,3.61,Female,No,Sun,Dinner,4


# create np-array

# 1. create 1D, 2D, 3D and 4D array using np.array()

In [5]:

arr1 = np.array([1, 2, 3, 4, 5])
print("1D Array:")
print(arr1)

arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print("\n2D Array:")
print(arr2)

arr3 = np.array([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])
print("\n3D Array:")
print(arr3)

arr4 = np.array([
    [
        [[1, 2], [3, 4]],
        [[5, 6], [7, 8]]
    ],
    [
        [[9, 10], [11, 12]],
        [[13, 14], [15, 16]]
    ]
])
print("\n4D Array:")
print(arr4)

1D Array:
[1 2 3 4 5]

2D Array:
[[1 2 3]
 [4 5 6]]

3D Array:
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]

4D Array:
[[[[ 1  2]
   [ 3  4]]

  [[ 5  6]
   [ 7  8]]]


 [[[ 9 10]
   [11 12]]

  [[13 14]
   [15 16]]]]


# create 1D, 2D, 3D and 4D array using arange() and reshape()

In [6]:

arr1 = np.arange(6)
print("1D Array:")
print(arr1)


arr2 = np.arange(12).reshape(3, 4)
print("\n2D Array:")
print(arr2)


arr3 = np.arange(24).reshape(2, 3, 4)
print("\n3D Array:")
print(arr3)


arr4 = np.arange(48).reshape(2, 2, 3, 4)
print("\n4D Array:")
print(arr4)

1D Array:
[0 1 2 3 4 5]

2D Array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

3D Array:
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]

4D Array:
[[[[ 0  1  2  3]
   [ 4  5  6  7]
   [ 8  9 10 11]]

  [[12 13 14 15]
   [16 17 18 19]
   [20 21 22 23]]]


 [[[24 25 26 27]
   [28 29 30 31]
   [32 33 34 35]]

  [[36 37 38 39]
   [40 41 42 43]
   [44 45 46 47]]]]


# create array using ones and zeros

In [7]:

ones_1d = np.ones(5)
print("1D Ones:")
print(ones_1d)


zeros_2d = np.zeros((3, 4))
print("\n2D Zeros:")
print(zeros_2d)


ones_2d = np.ones((2, 3))
print("\n2D Ones:")
print(ones_2d)


zeros_3d = np.zeros((2, 2, 3))
print("\n3D Zeros:")
print(zeros_3d)

1D Ones:
[1. 1. 1. 1. 1.]

2D Zeros:
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

2D Ones:
[[1. 1. 1.]
 [1. 1. 1.]]

3D Zeros:
[[[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]]


# using random

In [8]:

random_array = np.random.rand(5)
print("Random 1D Array:")
print(random_array)


random_2d = np.random.rand(3, 4)
print("\nRandom 2D Array:")
print(random_2d)


random_int = np.random.randint(1, 50, size=10)
print("\nRandom Integer Array:")
print(random_int)


random_int_2d = np.random.randint(1, 100, size=(3, 3))
print("\nRandom 2D Integer Array:")
print(random_int_2d)

Random 1D Array:
[0.70600563 0.26687849 0.29348993 0.01842085 0.15498477]

Random 2D Array:
[[0.44786604 0.19141842 0.66679416 0.59240652]
 [0.5270421  0.31097391 0.99409523 0.21508743]
 [0.34790829 0.94883866 0.99304983 0.71597472]]

Random Integer Array:
[35 30  1  9 36 29  4  1  9  7]

Random 2D Integer Array:
[[ 6 63 51]
 [66 44 58]
 [20 66 93]]


# using linspace

In [9]:

a = np.linspace(0, 10, 5)
print("5 values:")
print(a)


b = np.linspace(1, 20, 10)
print("\n10 values:")
print(b)


c = np.linspace(0, 1, 6)
print("\n6 values:")
print(c)

5 values:
[ 0.   2.5  5.   7.5 10. ]

10 values:
[ 1.          3.11111111  5.22222222  7.33333333  9.44444444 11.55555556
 13.66666667 15.77777778 17.88888889 20.        ]

6 values:
[0.  0.2 0.4 0.6 0.8 1. ]


# create 1D array of tip from tips dataframe

In [10]:
tip_array = tips['tip'].to_numpy()
print(tip_array)
print("\nDimension:", tip_array.ndim)

[ 1.01  1.66  3.5   3.31  3.61  4.71  2.    3.12  1.96  3.23  1.71  5.
  1.57  3.    3.02  3.92  1.67  3.71  3.5   3.35  4.08  2.75  2.23  7.58
  3.18  2.34  2.    2.    4.3   3.    1.45  2.5   3.    2.45  3.27  3.6
  2.    3.07  2.31  5.    2.24  2.54  3.06  1.32  5.6   3.    5.    6.
  2.05  3.    2.5   2.6   5.2   1.56  4.34  3.51  3.    1.5   1.76  6.73
  3.21  2.    1.98  3.76  2.64  3.15  2.47  1.    2.01  2.09  1.97  3.
  3.14  5.    2.2   1.25  3.08  4.    3.    2.71  3.    3.4   1.83  5.
  2.03  5.17  2.    4.    5.85  3.    3.    3.5   1.    4.3   3.25  4.73
  4.    1.5   3.    1.5   2.5   3.    2.5   3.48  4.08  1.64  4.06  4.29
  3.76  4.    3.    1.    4.    2.55  4.    3.5   5.07  1.5   1.8   2.92
  2.31  1.68  2.5   2.    2.52  4.2   1.48  2.    2.    2.18  1.5   2.83
  1.5   2.    3.25  1.25  2.    2.    2.    2.75  3.5   6.7   5.    5.
  2.3   1.5   1.36  1.63  1.73  2.    2.5   2.    2.74  2.    2.    5.14
  5.    3.75  2.61  2.    3.5   2.5   2.    2.    3.    3.48  

# create 2D array of tip and total_bill form tips dataframe

In [11]:
tip_total_bill = tips[['tip', 'total_bill']].to_numpy()
print(tip_total_bill)
print("\nShape:", tip_total_bill.shape)

[[ 1.01 16.99]
 [ 1.66 10.34]
 [ 3.5  21.01]
 [ 3.31 23.68]
 [ 3.61 24.59]
 [ 4.71 25.29]
 [ 2.    8.77]
 [ 3.12 26.88]
 [ 1.96 15.04]
 [ 3.23 14.78]
 [ 1.71 10.27]
 [ 5.   35.26]
 [ 1.57 15.42]
 [ 3.   18.43]
 [ 3.02 14.83]
 [ 3.92 21.58]
 [ 1.67 10.33]
 [ 3.71 16.29]
 [ 3.5  16.97]
 [ 3.35 20.65]
 [ 4.08 17.92]
 [ 2.75 20.29]
 [ 2.23 15.77]
 [ 7.58 39.42]
 [ 3.18 19.82]
 [ 2.34 17.81]
 [ 2.   13.37]
 [ 2.   12.69]
 [ 4.3  21.7 ]
 [ 3.   19.65]
 [ 1.45  9.55]
 [ 2.5  18.35]
 [ 3.   15.06]
 [ 2.45 20.69]
 [ 3.27 17.78]
 [ 3.6  24.06]
 [ 2.   16.31]
 [ 3.07 16.93]
 [ 2.31 18.69]
 [ 5.   31.27]
 [ 2.24 16.04]
 [ 2.54 17.46]
 [ 3.06 13.94]
 [ 1.32  9.68]
 [ 5.6  30.4 ]
 [ 3.   18.29]
 [ 5.   22.23]
 [ 6.   32.4 ]
 [ 2.05 28.55]
 [ 3.   18.04]
 [ 2.5  12.54]
 [ 2.6  10.29]
 [ 5.2  34.81]
 [ 1.56  9.94]
 [ 4.34 25.56]
 [ 3.51 19.49]
 [ 3.   38.01]
 [ 1.5  26.41]
 [ 1.76 11.24]
 [ 6.73 48.27]
 [ 3.21 20.29]
 [ 2.   13.81]
 [ 1.98 11.02]
 [ 3.76 18.29]
 [ 2.64 17.59]
 [ 3.15 20.08]
 [ 2.47 16

# practice atleast 2 example for each using ndim, shape, size and itemsize

In [12]:

a = np.array([1, 2, 3, 4, 5])
b = np.arange(12).reshape(3, 4)


print("ndim examples:")
print("a ndim =", a.ndim)
print("b ndim =", b.ndim)


print("\nshape examples:")
print("a shape =", a.shape)
print("b shape =", b.shape)


print("\nsize examples:")
print("a size =", a.size)
print("b size =", b.size)


print("\nitemsize examples:")
print("a itemsize =", a.itemsize, "bytes")
print("b itemsize =", b.itemsize, "bytes")

ndim examples:
a ndim = 1
b ndim = 2

shape examples:
a shape = (5,)
b shape = (3, 4)

size examples:
a size = 5
b size = 12

itemsize examples:
a itemsize = 8 bytes
b itemsize = 8 bytes


# change data type and memory size of any np-array using astype()

In [13]:
arr = np.array([1, 2, 3, 4, 5])

print("Original array:")
print(arr)
print("Original data type:", arr.dtype)
print("Original item size:", arr.itemsize, "bytes")


float_arr = arr.astype(float)

print("\nFloat array:")
print(float_arr)
print("New data type:", float_arr.dtype)
print("New item size:", float_arr.itemsize, "bytes")


int16_arr = arr.astype(np.int16)

print("\nInt16 array:")
print(int16_arr)
print("New data type:", int16_arr.dtype)
print("New item size:", int16_arr.itemsize, "bytes")

Original array:
[1 2 3 4 5]
Original data type: int64
Original item size: 8 bytes

Float array:
[1. 2. 3. 4. 5.]
New data type: float64
New item size: 8 bytes

Int16 array:
[1 2 3 4 5]
New data type: int16
New item size: 2 bytes


# create 2 same dimensional array and do scalar and vector operations

In [14]:
a = np.array([10, 20, 30, 40, 50])
b = np.array([1, 2, 3, 4, 5])

print("Array A:", a)
print("Array B:", b)

print("\nScalar Operations:")
print("A + 5 =", a + 5)
print("A - 5 =", a - 5)
print("A * 2 =", a * 2)
print("A / 2 =", a / 2)

print("\nVector Operations:")
print("A + B =", a + b)
print("A - B =", a - b)
print("A * B =", a * b)
print("A / B =", a / b)

Array A: [10 20 30 40 50]
Array B: [1 2 3 4 5]

Scalar Operations:
A + 5 = [15 25 35 45 55]
A - 5 = [ 5 15 25 35 45]
A * 2 = [ 20  40  60  80 100]
A / 2 = [ 5. 10. 15. 20. 25.]

Vector Operations:
A + B = [11 22 33 44 55]
A - B = [ 9 18 27 36 45]
A * B = [ 10  40  90 160 250]
A / B = [10. 10. 10. 10. 10.]


# find minimun and maximum tip

In [15]:
tip_array = tips['tip'].to_numpy()

minimum_tip = np.min(tip_array)
maximum_tip = np.max(tip_array)

print("Minimum tip:", minimum_tip)
print("Maximum tip:", maximum_tip)

Minimum tip: 1.0
Maximum tip: 10.0


# find average total_bill and average tip

In [16]:
total_bill_array = tips['total_bill'].to_numpy()
tip_array = tips['tip'].to_numpy()

average_total_bill = np.mean(total_bill_array)
average_tip = np.mean(tip_array)

print("Average total bill:", average_total_bill)
print("Average tip:", average_tip)

Average total bill: 19.78594262295082
Average tip: 2.99827868852459


# find median total_bill

In [17]:
total_bill_array = tips['total_bill'].to_numpy()
median_total_bill = np.median(total_bill_array)
print("Median total bill:", median_total_bill)

Median total bill: 17.795


# find standard deviasion and variance of tip

In [18]:
tip_array = tips['tip'].to_numpy()

standard_deviation = np.std(tip_array)
variance = np.var(tip_array)

print("Standard deviation of tip:", standard_deviation)
print("Variance of tip:", variance)

Standard deviation of tip: 1.3807999538298954
Variance of tip: 1.9066085124966412


# find log values of tip

In [19]:
tip_array = tips['tip'].to_numpy()
log_tip = np.log(tip_array)

print("Original tip values:")
print(tip_array)

print("\nLog values of tip:")
print(log_tip)

Original tip values:
[ 1.01  1.66  3.5   3.31  3.61  4.71  2.    3.12  1.96  3.23  1.71  5.
  1.57  3.    3.02  3.92  1.67  3.71  3.5   3.35  4.08  2.75  2.23  7.58
  3.18  2.34  2.    2.    4.3   3.    1.45  2.5   3.    2.45  3.27  3.6
  2.    3.07  2.31  5.    2.24  2.54  3.06  1.32  5.6   3.    5.    6.
  2.05  3.    2.5   2.6   5.2   1.56  4.34  3.51  3.    1.5   1.76  6.73
  3.21  2.    1.98  3.76  2.64  3.15  2.47  1.    2.01  2.09  1.97  3.
  3.14  5.    2.2   1.25  3.08  4.    3.    2.71  3.    3.4   1.83  5.
  2.03  5.17  2.    4.    5.85  3.    3.    3.5   1.    4.3   3.25  4.73
  4.    1.5   3.    1.5   2.5   3.    2.5   3.48  4.08  1.64  4.06  4.29
  3.76  4.    3.    1.    4.    2.55  4.    3.5   5.07  1.5   1.8   2.92
  2.31  1.68  2.5   2.    2.52  4.2   1.48  2.    2.    2.18  1.5   2.83
  1.5   2.    3.25  1.25  2.    2.    2.    2.75  3.5   6.7   5.    5.
  2.3   1.5   1.36  1.63  1.73  2.    2.5   2.    2.74  2.    2.    5.14
  5.    3.75  2.61  2.    3.5   2.5   2. 

# apply round, floor and ceil operation on tip array

In [20]:
tip_array = tips['tip'].to_numpy()

print("Original tip values:")
print(tip_array)

print("\nRounded values:")
print(np.round(tip_array))

print("\nFloor values:")
print(np.floor(tip_array))

print("\nCeil values:")
print(np.ceil(tip_array))

Original tip values:
[ 1.01  1.66  3.5   3.31  3.61  4.71  2.    3.12  1.96  3.23  1.71  5.
  1.57  3.    3.02  3.92  1.67  3.71  3.5   3.35  4.08  2.75  2.23  7.58
  3.18  2.34  2.    2.    4.3   3.    1.45  2.5   3.    2.45  3.27  3.6
  2.    3.07  2.31  5.    2.24  2.54  3.06  1.32  5.6   3.    5.    6.
  2.05  3.    2.5   2.6   5.2   1.56  4.34  3.51  3.    1.5   1.76  6.73
  3.21  2.    1.98  3.76  2.64  3.15  2.47  1.    2.01  2.09  1.97  3.
  3.14  5.    2.2   1.25  3.08  4.    3.    2.71  3.    3.4   1.83  5.
  2.03  5.17  2.    4.    5.85  3.    3.    3.5   1.    4.3   3.25  4.73
  4.    1.5   3.    1.5   2.5   3.    2.5   3.48  4.08  1.64  4.06  4.29
  3.76  4.    3.    1.    4.    2.55  4.    3.5   5.07  1.5   1.8   2.92
  2.31  1.68  2.5   2.    2.52  4.2   1.48  2.    2.    2.18  1.5   2.83
  1.5   2.    3.25  1.25  2.    2.    2.    2.75  3.5   6.7   5.    5.
  2.3   1.5   1.36  1.63  1.73  2.    2.5   2.    2.74  2.    2.    5.14
  5.    3.75  2.61  2.    3.5   2.5   2. 

# use 1D, 2D and 3D np-array, and apply indexing and slicing atleast 5 example for each (take example as your wish)

In [21]:

arr1 = np.array([10, 20, 30, 40, 50, 60, 70, 80])

print("1D Array:")
print(arr1)

print("\nExample 1:", arr1[0])

print("Example 2:", arr1[-1])

print("Example 3:", arr1[3])

print("Example 4:", arr1[:3])

print("Example 5:", arr1[2:6])


arr2 = np.arange(1, 13).reshape(3, 4)

print("2D Array:")
print(arr2)

print("\nExample 1:")
print(arr2[0])

print("Example 2:", arr2[0, 0])

print("Example 3:", arr2[-1, -1])

print("Example 4:")
print(arr2[:2])

print("Example 5:")
print(arr2[:, :2])

arr3 = np.arange(1, 25).reshape(2, 3, 4)

print("3D Array:")
print(arr3)

print("\nExample 1:")
print(arr3[0])

print("Example 2:", arr3[0, 0, 0])

print("Example 3:", arr3[-1, -1, -1])

print("Example 4:")
print(arr3[0, 0, :])

print("Example 5:")
print(arr3[0, :, :2])

1D Array:
[10 20 30 40 50 60 70 80]

Example 1: 10
Example 2: 80
Example 3: 40
Example 4: [10 20 30]
Example 5: [30 40 50 60]
2D Array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Example 1:
[1 2 3 4]
Example 2: 1
Example 3: 12
Example 4:
[[1 2 3 4]
 [5 6 7 8]]
Example 5:
[[ 1  2]
 [ 5  6]
 [ 9 10]]
3D Array:
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]

Example 1:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Example 2: 1
Example 3: 24
Example 4:
[1 2 3 4]
Example 5:
[[ 1  2]
 [ 5  6]
 [ 9 10]]


# stacking and spliting

In [22]:
d = np.arange(27).reshape(3,9)
e = np.arange(28,55).reshape(3,9)

# use hstack() and vstack()

In [23]:
print("Array D:")
print(d)

print("\nArray E:")
print(e)

horizontal = np.hstack((d, e))

print("\nHorizontal Stack:")
print(horizontal)

vertical = np.vstack((d, e))

print("\nVertical Stack:")
print(vertical)

Array D:
[[ 0  1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16 17]
 [18 19 20 21 22 23 24 25 26]]

Array E:
[[28 29 30 31 32 33 34 35 36]
 [37 38 39 40 41 42 43 44 45]
 [46 47 48 49 50 51 52 53 54]]

Horizontal Stack:
[[ 0  1  2  3  4  5  6  7  8 28 29 30 31 32 33 34 35 36]
 [ 9 10 11 12 13 14 15 16 17 37 38 39 40 41 42 43 44 45]
 [18 19 20 21 22 23 24 25 26 46 47 48 49 50 51 52 53 54]]

Vertical Stack:
[[ 0  1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16 17]
 [18 19 20 21 22 23 24 25 26]
 [28 29 30 31 32 33 34 35 36]
 [37 38 39 40 41 42 43 44 45]
 [46 47 48 49 50 51 52 53 54]]


# use hsplit() and vsplit()

In [24]:
print("Array D:")
print(d)

print("\nHorizontal Split of D into 3 parts:")
h_split = np.hsplit(d, 3)

for i, part in enumerate(h_split):
    print(f"\nPart {i + 1}:")
    print(part)

vertical_array = np.arange(24).reshape(6, 4)

print("\nVertical Array:")
print(vertical_array)

print("\nVertical Split into 2 parts:")
v_split = np.vsplit(vertical_array, 2)

for i, part in enumerate(v_split):
    print(f"\nPart {i + 1}:")
    print(part)

Array D:
[[ 0  1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16 17]
 [18 19 20 21 22 23 24 25 26]]

Horizontal Split of D into 3 parts:

Part 1:
[[ 0  1  2]
 [ 9 10 11]
 [18 19 20]]

Part 2:
[[ 3  4  5]
 [12 13 14]
 [21 22 23]]

Part 3:
[[ 6  7  8]
 [15 16 17]
 [24 25 26]]

Vertical Array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]

Vertical Split into 2 parts:

Part 1:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Part 2:
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
